#!/usr/bin/env python3
from pathlib import Path
import json,hashlib,datetime
R=Path(__file__).resolve().parents[3];O=R/'phase2/assumptions'
SN='sources/repos/RickKessler__SNANA/src/snlc_fit.F90';CFG='sources/repos/des-science__DES-SN5YR@1.3/7_PIPPIN_FILES/base_files/lcfit/lcfit_desSMP_5yr.nml';PAPER='papers/text/2406.05046v1.txt'
def source(p,lo,hi,url=None):
 if url is None:
  if p==SN:url=f'https://github.com/RickKessler/SNANA/blob/886408a4e171896db5eaa97e735a655f50cec2db/src/snlc_fit.F90#L{lo}-L{hi}'
  elif p==CFG:url=f'https://github.com/des-science/DES-SN5YR/blob/e3493cb3b9505fc1f3f392d887364b50dae21439/7_PIPPIN_FILES/base_files/lcfit/lcfit_desSMP_5yr.nml#L{lo}-L{hi}'
  else:url='https://arxiv.org/abs/2406.05046'
 return {'path':p,'lines':[lo,hi],'url':url,'sha256':hashlib.file_digest((R/p).open('rb'),'sha256').hexdigest()}
rows=[]
def add(id,assumption,why,falsifier,status,result,limits,sources,artifacts):rows.append(dict(id=id,assumption=assumption,why_needed=why,empirical_falsifier=falsifier,status=status,result=result,identifiability=limits,sources=sources,artifacts=artifacts))
add('M01','Released FLUXCAL is calibrated signed flux on 27.5mag scale; it is not raw detector counts. Corrections already embedded must not be applied twice.','Sets physical meaning and prevents duplicate host-error/DCR/chromatic corrections.','Source README/config contradictions or raw-vs-LCPLOT amplitude disagreement.','supported_with_limits','Release config comments disable already embedded corrections. Targeted raw-vs-published LCPLOT agrees to text precision. DR2 calibrated CCD images obtained independently are in electrons.','This verifies representation, not the physical correctness of every applied correction.',[source(CFG,50,55),source(PAPER,370,425)],['phase2/data_audit/lcplot_audit.json','phase2/assumptions/pixel_noise_results.json'])
add('M02','Quadratic flux residual objective is adequate for the accepted measurements after covariance and clipping.','Needed to interpret parameter estimates and reported fit uncertainty as a measurement likelihood.','Off-signal/held-out standardized residuals have systematic offsets, excessive width/tails or dependence unexplained by known contamination.','falsified_for_naive_DIFFIMG_zero_baseline_model_not_SMP','Quality DIFFIMG >365day mean-0.861,RMS2.944; heldout cross-season baseline with conservative propagated uncertainty mean-0.038,RMS1.664 and >3tail5.16%. SMP >200day robust width1.054 but heavy tails; SMP has zero >365day support.','DIFFIMG has older reduction, baseline contamination and non-cosmology optimization. No direct proof of SMP likelihood failure or cosmology bias. Published residuals are fit/clipping conditioned.',[source(SN,4294,4340),source(PAPER,257,290)],['phase2/assumptions/off_signal_statistics.json','phase2/assumptions/off_signal_followup.json','phase2/assumptions/published_residual_statistics.json'])
add('M03','Measurement errors enter the covariance diagonal unless explicit data covariance fudge is requested. SALT model and MW covariance are separately nonzero.','Independent measurement-error treatment can overweight repeated/shared-reference errors.','Exact full-row repetitions or shared-baseline/neighbor dependence unexplained by the implemented model/MW covariance.','partially_falsified_as_record_independence_not_quantified_parameter_bias','Measurement variance only diagonal at10703–10706; COVFUDGE_DATA returns0 for blank default; model+MW terms retained. Exact full-record repeat pairs4328 across1550objects. Shared off-signal offsets detected in DIFFIMG.','Repeated field key alone does not prove a duplicated independent measurement: A/B variants often differ in detector coordinates. Exact records strongly challenge treating all rows as new information, but parent measurement lineage and impact require controlled refit.',[source(SN,10694,10712),source(SN,6896,6898),source(SN,14808,14846)],['phase2/data_audit/exact_duplicates.json','phase2/data_audit/duplicate_identity.json','phase2/assumptions/off_signal_pair_statistics.json','phase2/assumptions/off_signal_followup.json'])
add('M04','SMP galaxy/reference modeling and nightly inverse-variance averaging adequately marginalize shared image/scene uncertainties.','A galaxy scene and astrometric centroid fitted jointly across epochs can correlate flux errors; nightly averaging assumes the relevant independence or covariance treatment.','Recovered image/scene posterior yields additional epoch covariance, or heldout reference-season baselines show unmodeled structure.','not_identifiable_from_released_SMP_flux_alone','Public paper describes joint transient+host fit, posterior-derived flux errors, source/hostPoisson additions and nightly averaging; PHOT supplies scalar uncertainties, not scene posterior or full epoch covariance.','Generic public images exist and have been acquired, but exact per-SN reference selection/PSF/scene posterior/zeropoint lineage was not recovered. SMP assumes zero flux outside -40..+300day fit region; released free-flux points cannot test >365day zero-reference assumption.',[source(PAPER,259,299),source(PAPER,352,425)],['phase2/assumptions/image_access/stamp_manifest.json','phase2/data_audit/contract.json'])
add('M05','Negative measurements are valid signed flux likelihood inputs; very negative observations are subject to configured rejection.','Dropping all negative points would bias faint/late flux upward.','Loader positivity censoring or evidence of a more restrictive SNR cutoff than documented.','code_verified','Flux residual uses signed FLUXCAL. Default SIGNOISE_REJECT=-9.0; first-iteration rejects below it, in addition to chi-square and phase. Millions of public DIFFIMG and517801SMP records are negative.','Negative retention alone does not validate error distribution or sample detection selection.',[source(SN,4298,4330),source(SN,4457,4490),source(SN,6738,6738)],['phase2/data_audit/summary.json'])
add('M06','Clipping at first iteration selects an adequate and reproducible set of observations.','Data-dependent masks can change optimizer basin and invalidate naive accepted-residual Gaussian checks.','Different valid starts/versions or fixed-mask arm produce materially different parameters/masks.','observed_nonreproducibility_under_investigation','DELCHI2_REJECT10 and first-iteration phase/SNR clipping implemented. CID1256426 has7mask switches between public and refit among same27available records; no corresponding changedflux correction. Conditioned published mask preserves62702acceptedrecords/1635objects.','Fixed published mask is conditional on original fit, not independent validation.94ambiguous groups,93 retain all candidate multiplicities; one subset ambiguity disclosed.',[source(CFG,64,74),source(SN,4457,4490)],['phase2/data_audit/lcplot_audit_mask32.json','phase2/assumptions/conditional_mask/manifest.json','phase2/assumptions/conditional_mask/ambiguity.json'])
add('M07','Published filter transmission/zero-point calibration and rest-wavelength coverage adequately map observed flux to SALT spectral flux.','Broadband amplitudes and colors depend on passband+calibration; a scalar exposure zeropoint does not encode chromatic corrections.','Heldout-band flux residual pattern inconsistent with calibration covariance or independently reconstructed standards/transmission.','inputs_available_physical_validation_pending','Pinned calibration FITS and SALT3.DES5YR available; configured3500..8000Angstrom restframe andgriz. Original/current PHOT bytesidentical despite calibration/model release updates, so Dovekie distances are not new measured lightcurves.','Successful use of released calibration is reproducibility, not independent proof. Exact SMP tertiary-star/PSF correction lineage not reconstructed in this wave.',[source(CFG,10,12),source(CFG,50,62),source(PAPER,211,238)],['phase2/data_audit/summary.json','phase2/data_audit/flux_colour_holdout_preregistration.json','phase2/official/inputs/sndata-inventory.txt'])
add('M08','MW extinction is adequately represented by Schlafly-updated E(B-V), Fitzpatrick99 Rv3.1 and its implemented covariance.','Foreground reddening covaries band flux and inferred SN color.','Residuals correlate with independently measured MW reddening or alternate foreground-law prediction improves heldout bands.','config_verified_physical_test_pending','OPT_MWEBV3,OPT_MWCOLORLAW99,RV3.1; covariance uses products of epoch MWfluxerrors across bands.','No claim this fixed law is universally true; no alternate-law fit passed baselinegate yet.',[source(CFG,22,25),source(SN,10694,10700)],['phase2/data_audit/flux_colour_holdout_preregistration.json'])
add('M09','Published scalar uncertainties and quality masks characterize the analysis-eligible observational subset.','Mask meaning changes across reductions; silently transplanting DIFFIMG bits can discard accepted SMP epochs.','Accepted published records contradict proposed flag rejection rule.','blanket_DIFFIMG_to_SMP_mask_falsified','Public accepted SMP includesbit2,1024,2048; unambiguous acceptedbits4..512excluding2 arezero. Mask32 explains two pilot epoch-count differences but not fullbaseline.','Observed flagbit distributions are empirical constraints, not complete author mask reconstruction;2accepted rows have possiblebit32 ambiguity.',[source(CFG,34,55)],['phase2/data_audit/published_lcplot_flags.json','phase2/data_audit/lcplot_audit_mask32.json'])
add('M10','Selected observed lightcurves and missing hosts/redshifts are correctly conditioned in inference.','Detection, host-z acquisition and SALT/BBC selection are not missing-at-random observations.','Exactcut/denominator inconsistency or selection response changes with latent host/color/redshift not in model.','structural_audit_complete_selection_model_external','All pointers/NOBS rows verify; DES19706SMP versus31636DIFFIMG and1635originalHubble objects are distinct selection levels. Header redshift/host missingness substantial.','Our off-signal test uses selectedHubbleCIDs, not complete detection universe. No complete flux-based selection normalization inferred from accepted sample alone.',[source(CFG,30,47),source(PAPER,268,280)],['phase2/data_audit/summary.json','phase2/data_audit/verification.json','docs/phase2/literature-selection.md'])
add('M11','CCD weight map describes local stochastic image noise and weak pixel covariance adequately for a bounded aperture diagnostic.','This is an independent measurement-level check below SNANA and calibrated lightcurve reduction.','Unmasked blank/control pixels and apertures depart strongly from weight-derived variance, or WCS/exposure identity fails.','bounded_consistency_not_survey_validation','3matched exposures230179g/230180r/230181i atCCD17: exact science crop/weight alignment confirmed, source-screened pixelRMS1.009/1.002/.999 and neighbor products.004–.011;42/40/43screened aperturecontrolsRMS.865/.930/1.061.','OneSNfield, one observingnight, source-screen conditioned tails, DR2processing not guaranteed exactSMP inputs. No PSFscene refit or cosmological conclusion.',[],['phase2/assumptions/pixel_noise_preregistration.json','phase2/assumptions/pixel_noise_results.json','phase2/assumptions/image_access/complete_science_manifest.json','phase2/assumptions/image_access/weight_access_manifest.json'])
add('M12','REDCOV0.6 in simulation should be interpreted as correlation of added error-fudge noise, not total observed flux correlation.','A wrong covariance convention would make data-vs-simulation comparisons misleading.','Code algebra or public flux covariance disagrees with the chosen interpretation.','code_convention_verified_by_selection_agent','Historical snlc_sim.c adds fudgevariance(scale²−1)*searchvariance, covariance0.6*sqrt(F_iF_j) withinband/field; independentsearch and fullycorrelatedtemplate terms separate.','Off-signal raw-pull correlation includes offsets and realvariability and cannot directly estimate thiscomponent coefficient.',[],['docs/phase2/literature-selection.md','phase2/assumptions/off_signal_pair_statistics.json'])
add('M13','Reported fitted SALT parameter covariance is numerically compatible with a Gaussian likelihood.','A downstream hierarchy requires usable joint uncertainties, not rounded/incompatible entries.','Negative eigenvalues or correlations>|1| after faithful public-error reconstruction.','naive_public_covariance_interpretation_falsified_for_subset','Original metadata5nonPSD,current11; most originalx0crosscov roundedzero. Code documents MINOSdiagonal/paraboliccross mismatch and optionalrepair.','Does not prove original optimizer likelihood invalid. Use independently output fullcovariance and report any repair, not silent PSD projection.',[source(SN,2534,2560)],['phase2/data_audit/fitted_parameter_covariances.npz','phase2/data_audit/summary.json'])
for row in rows:
 if row['id']=='M12':
  row['sources']=[source('phase2/official/build/SNANA-2fe0f56/src/snlc_sim.c',24299,24314,'https://github.com/RickKessler/SNANA/blob/2fe0f56/src/snlc_sim.c#L24299-L24314'),source('phase2/official/build/SNANA-2fe0f56/src/snlc_sim.c',24443,24513,'https://github.com/RickKessler/SNANA/blob/2fe0f56/src/snlc_sim.c#L24443-L24513'),source('phase2/official/inputs/SNDATA_ROOT/simlib/DES/DES-SN5YR_DES_FLUXERRMODEL_SIM.DAT',19,23,'https://zenodo.org/records/12655677')]
(O/'assumption_register.json').write_text(json.dumps({'schema':'des-measurement-assumption-register-v1','created_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'scope':'Public calibrated photometry and independently acquired calibrated detector image planes; original detector raw science/calibration images documented public but not needed/acquired for this bounded test.','source_version_note':'Current pinned SNANA code is not asserted identical to unpublished original executable. Effective default crosscheck supplied by official reproduction agent; separate code/minimizer register there.','assumptions':rows},indent=2)+'\n')
print(len(rows),'assumptions')
