"""Build a capability-overlap map using stable catalogue identities."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parent
records = {int(r['id'].split('-')[1]):r for r in json.loads((ROOT/'catalogue.json').read_text())}
rows = []
def add(capability, ids, relationship, opportunity, preserve):
    refs = [records[i] for i in ids]
    rows.append(dict(capability=capability, catalogue_ids=[r['id'] for r in refs], relationship=relationship, consolidation_opportunity=opportunity, distinctions_to_preserve=preserve))

add('FITS reading and writing', [1,7,355,434,524], 'Both independent interfaces and wrappers around CFITSIO.', 'One shared reader/writer layer, header handling, memory mapping and compression service.', 'Astropy is not simply another CFITSIO wrapper; FITS scaling, nulls, masks, extension types and ownership differ.')
add('Scientific arrays and file containers', [4,11,17,494,495,496,497,498], 'Related storage and data-model roles at different layers.', 'Common in-memory arrays, named dimensions and adapters; avoid repeated materialization and conversions.', 'HDF5/Zarr/ASDF/NDF are not interchangeable schemas. Preserve units, WCS, quality and variance rather than only array values.')
add('Tables, joins, catalogue queries and columnar data', [1,414,500,501,502,503,504], 'Overlapping generic table operations with different execution models.', 'Shared typed catalogue objects, joins, filters and query execution.', 'Sky-coordinate joins differ from ordinary equijoins; nulls, masks, units and integer precision matter.')
add('Archive access and local/remote caching', [2,3,24,310,505], 'Complementary access layers with overlapping connection/cache concerns.', 'One resource manager, credentials boundary, download cache and dataset identity scheme.', 'VO discovery, mission archive APIs and filesystem range requests require separate adapters.')
add('Units, constants, epochs and positional transformations', [1,8,9,10,22,23,32,356,357,359,430,431,432], 'Shared lineage and partially overlapping independent implementations.', 'Common physical-quantity, epoch, frame and ephemeris services.', 'SOFA/ERFA ancestry; Earth-orientation tables; leap seconds; observer location; precision and frame conventions.')
add('WCS, reprojection and mosaicking', [1,5,6,10,16,45,57,63], 'Wrappers plus independent reprojection and coaddition implementations.', 'Reuse coordinate transforms, resampling plans and exposure geometry.', 'Distortion models, flux versus surface brightness, correlated noise and pixel-area conventions.')
add('Sky indexing, coverage and spherical transforms', [12,13,14,185,186,435,436,508,509,510], 'Related indexing algorithms, some wrappers and different transform engines.', 'Shared sky geometry and transform backends, with reusable mask/window operators.', 'HEALPix indexing is not a spherical-harmonic transform; MOC coverage is not a science map; spin, ordering and normalization differ.')
add('Pipeline orchestration and calibration selection', [36,59,65,66,67,68,69,70,71,122,499,527,528], 'Different task systems repeatedly manage dependencies, files and execution.', 'One task graph, artifact catalogue and cache mechanism; retain domain recipes.', 'A generic scheduler does not replace instrument calibration rules or scientific data-quality gates.')
add('Detector correction, masking and cosmic-ray removal', [27,29,30,39,40,61,62,64,81,462], 'Independent tasks plus shared algorithm lineage.', 'Reusable bias/dark/flat, noise, masking and rejection operations.', 'Detector models, gain, saturation, ramp sampling and propagated uncertainty are instrument-dependent.')
add('Detection, segmentation and deblending', [38,41,42,53,123,124,125,455,463], 'Shared ancestry in some pairs and distinct methods elsewhere.', 'Common image/cube detection primitives, segmentation objects and catalogue outputs.', 'SEP derives from Source Extractor; scarlet-style source models, radio detection and cube clumps are not identical methods.')
add('PSF, aperture and crowded-field photometry', [38,43,47,48,49,52,360,361,469], 'Partially overlapping measurement tasks.', 'Shared PSF objects, aperture integrals, fitting primitives and uncertainty outputs.', 'Spatial PSFs, crowding, multiband constraints, forced positions and detector calibration change the inference.')
add('Galaxy image modelling and morphology', [50,51,52,53,54,148,456], 'Overlapping image forward models; different reconstruction and fitting methods.', 'Common image formation, PSF convolution, source profiles and fit-data contracts.', 'Parametric structure, nonparametric morphology, deblending and lens-source reconstruction remain distinct scientific operations.')
add('Image subtraction and time-series detection', [55,56,67,469], 'Similar workflow goals and related difference-imaging algorithms.', 'Shared registration, convolution, difference-image uncertainty and detection products.', 'Kernel basis, noise model, reference-image construction and detection selection must remain explicit.')
add('Spectral reduction, extraction and line fitting', [18,58,59,73,74,75,76,77,78,79,80,461], 'Repeated generic primitives inside instrument and survey workflows.', 'Common spectrum objects, wavelength grids, masks, response functions and extraction/fitting interfaces.', 'Pixel covariance, instrumental line spread, sky subtraction and redshift/template assumptions.')
add('Synthetic photometry, extinction and SED transformations', [19,20,21,196,222,224,225,226,227,228,229,230,457], 'Repeated passband integration and attenuation operations across different physical models.', 'Share passbands, extinction laws, interpolation and magnitude/flux conversions.', 'Rest/observer frame, photon/energy weighting, zero-points, wavelength ranges and model validity.')
add('High-energy event filtering, response folding and spectra', [82,83,84,88,89,90,91,92,95,96,97,99], 'Overlapping analysis operations in mission and modelling ecosystems.', 'Shared event lists, good-time intervals, responses, likelihood interfaces and model evaluation.', 'Response definitions, Poisson backgrounds, plasma models and mission calibration are not automatically interchangeable.')
add('Timing, period searches and stochastic signals', [1,85,93,94,136,139,140,141,320,395,468], 'Related signal-analysis primitives with domain-specific timing models.', 'Common time-series, Fourier, windowing, period-search and covariance operations.', 'Pulsar barycentric timing is more than a periodogram; irregular sampling, exposure and noise models differ.')
add('Radio calibration and visibility imaging', [106,107,108,110,111,112,114,115,116,117,118,119,120,122], 'Alternative pipelines and solvers around related measurement equations.', 'One visibility data model, Jones operators, flagging interfaces, gridding and calibration products.', 'Direction-dependent gains, beam models, weighting, wide-field approximations and solver degeneracies.')
add('VLBI and optical-interferometric reconstruction', [131,132,133,364,365,450,451,452,453,454], 'Related inverse problems with different observables and regularizers.', 'Shared Fourier-domain operators, closure quantities and reconstruction interfaces.', 'Radio visibilities, optical squared visibilities and closure phases carry different calibration and likelihood information.')
add('Strong-lens potentials, ray tracing and source inference', [147,148,149,150,151,152,153,154,155,156,157], 'Independent implementations, ports and competing reconstruction methods.', 'Common lens potentials, deflections, Jacobians, multiple-plane geometry and image formation.', 'Source bases, priors, mass-sheet degeneracy, boundary conditions and supported mass models.')
add('Lensing time delays, microlensing and coherent waves', [158,159,160,161,162,163,493], 'Connected problems; not one interchangeable solver family.', 'Reuse distances, trajectories, source profiles, lens geometry and likelihood plumbing.', 'Time-delay cosmography, finite-source microlensing and wave-optics diffraction require different numerical engines.')
add('Weak-lensing shapes, simulation and calibration', [164,165,166,167,168,479], 'Shared lineage in some tools and distinct measurement/calibration stages.', 'Common PSF/image operators, shear conventions, catalogues, masks and correlation primitives.', 'Metacalibration, detection effects and selection response are part of the estimator; JAX-GalSim is labelled early development.')
add('Background cosmology, distances, ages and growth', [1,169,170,175,176,177,358,369,370], 'Many packages expose overlapping background calculations.', 'One versioned background solution and interpolation service per cosmological model and parameter state.', 'Neutrinos, radiation, curvature, dark energy and numerical tolerances must be in the cache key and interface.')
add('Einstein–Boltzmann, power-spectrum and perturbation calculations', [169,170,175,177,178,179,180,181,369,370,521,522,523], 'Independent solvers, ports, approximations and trained surrogates.', 'Reuse background histories, transfer functions, transform kernels and requested observable grids.', 'Linear/nonlinear regimes, EFT terms, gauge, neutrinos, normalization and emulator training support. A surrogate is not independent validation of its training solver.')
add('Correlations, power estimators and survey windows', [167,182,183,184,185,186], 'Different estimators with overlapping pair-count and Fourier primitives.', 'Shared catalogue selections, pair counts, transforms, binning and window operators.', 'Estimator normalization, random catalogues, masks, shot noise, weights and covariance conventions.')
add('Cosmological likelihood and parameter pipelines', [171,172,173,174,190,193,194], 'Different orchestration systems, sometimes calling the same theory engines or datasets.', 'Common theory-product cache, parameter graph, likelihood interfaces and chain interchange.', 'Shared data and calibration create covariance; identical theory engines are not independent scientific checks.')
add('Supernova and transient modelling', [195,196,197,198,199,200,201,202,203,204], 'Partly overlapping light-curve, spectral, training and inference work.', 'Shared observations, filters, redshifts, time grids, model adapters and selection simulations.', 'SALT-family fitting, BayeSN, template classification and physical transients are different models; preserve training and calibration lineage.')
add('Stellar populations and galaxy SED inference', [213,216,217,218,219,220,221,222,223,224,225,226,227,457], 'Nested physical layers with overlapping fitting and population interfaces.', 'Reusable stellar libraries, population integration, dust/emission components and observation projection.', 'Stellar evolution, binary populations, synthesis and SED fitting are distinct levels; IMF and evolutionary tracks remain explicit.')
add('Radiative transfer, ionization and spectral microphysics', [205,206,231,232,233,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,488], 'Related physics with different regimes and numerical formulations.', 'Share atomic/molecular data access, opacity/emissivity objects and transport interfaces.', 'LTE/non-LTE, scattering, polarization, velocity fields, geometry and equilibrium assumptions define separate solvers.')
add('N-body gravity, hydro and magnetohydrodynamics', [25,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,274,275,384,471,472,492], 'Independent numerical methods with shared mesh/particle, time-step and communication needs.', 'Common particle/mesh objects, initial conditions, gravity and microphysics interfaces, checkpointing and diagnostics.', 'SPH, meshless, moving mesh, AMR, direct N-body and low-Mach methods must not be collapsed into one undocumented approximation.')
add('Simulation readers, halo finding and dynamical analysis', [277,278,279,280,281,282,473,474,475,476], 'Analysis layers overlap on readers, units, selections and particle data.', 'One snapshot reader layer, spatial indexing, units and output catalogue format.', 'Halo definitions, unbinding, merger-tree construction and dynamics models can change scientific results.')
add('Symbolic geometry, geodesics and numerical relativity', [283,284,285,286,287,288,289,290,291,292,293,294,298,299,300,301,302,303,366,367,368,470], 'Several physically related but numerically distinct levels.', 'Share tensor conventions, metric definitions, geometric primitives and diagnostics where valid.', 'Symbolic equations, fixed-spacetime ray tracing and evolving Einstein equations are different jobs; gauge and formulation must remain visible.')
add('Gravitational-wave signals, likelihoods and populations', [306,307,308,309,311,312,313,314,315,316,317,318,319], 'Shared waveform libraries plus alternative search and inference pipelines.', 'Common strain/PSD data, waveform calls, detector responses, likelihood products and posterior formats.', 'Search detection, event inference and population selection are different levels; calibration and waveform approximations matter.')
add('Generic optimization, sampling and posterior summaries', [89,171,308,386,387,388,389,390,391,392,393,394,466,514,515,525,526], 'Some shared optimizer ancestry, many independent algorithms and repeated adapters.', 'Common parameter transforms, likelihood/gradient interfaces, diagnostics and sample schemas.', 'Least squares, MCMC, nested sampling, variational inference and optimization are not equivalent statistical procedures.')
add('Dense/sparse linear algebra, FFTs, quadrature and ODEs', [371,374,375,377,378,379,380,381,382,383,427,428,429,437,438,439,507,508,511,512,513,514,515,516,517,518,519,520], 'Frequently shared underlying engines or historical algorithm families beneath many frontends.', 'Central numerical services, memory layout, thread pools, transform/factorization plans and tolerance conventions.', 'Backend choice, conditioning, precision, stiffness, convergence criteria and deterministic execution; common ancestry reduces independence.')
add('Visualization and analysis applications', [35,413,414,415,416,417,418,419,420,421,422,464,465], 'Repeated readers, selections, plotting and interactive inspection across applications.', 'One linked observation/catalogue viewer backed by shared objects, selections and provenance.', 'Preserve image, spectrum, cube, sky-map, event and simulation-specific interactions rather than forcing a single generic plot.')

assert len(rows)==36
(ROOT/'overlap-map.json').write_text(json.dumps(rows,indent=2,ensure_ascii=False)+'\n')

out = ['# Where cosmology software repeats work', '',
    'This companion groups the survey by jobs rather than package names. It covers the full path from raw files and archives through calibration, measurement, physical calculations, simulation, inference and inspection. The 36 families below identify **capability overlap and consolidation opportunities**. They are not measurements of redundant runtime or proof that all listed programs use the same algorithms.', '',
    'The useful distinction is between four kinds of overlap:', '',
    '1. **One engine behind several interfaces.** CFITSIO is exposed through Python fitsio, Julia FITSIO and Rust fitsio. Calling these separate packages does not mean three independently developed FITS engines.',
    '2. **Related code or algorithm ancestry.** SEP and Source Extractor, Astro-SCRAPPY and L.A.Cosmic, SOFA and ERFA, and MINPACK-related fitters belong to identifiable lineages.',
    '3. **Independent implementations of similar calculations.** CAMB and CLASS, several lens modelling packages, radio imagers and stellar-population fitters overlap in purpose. Their independence can be valuable for checking results.',
    '4. **Repeated workflow work.** Loading the same observations, converting arrays, computing the same background distances, convolving the same response or rebuilding a covariance factorization can happen at application boundaries. Whether a particular workflow actually repeats it requires profiling and dependency inspection.', '',
    'The individual projects and primary sources are linked in each row. The consolidation column is a survey synthesis, not a claim that an upstream package endorses this design.', '',
    '## End-to-end scope', '',
    '| Stage | Inputs and repeated operations to inventory | Relevant families |', '|---|---|---|',
    '| Acquire and decode | Archive queries, remote reads, FITS/HDF5/Zarr/ASDF, catalogue files, event streams, visibilities, simulation snapshots | Astroquery, PyVO, CFITSIO, h5py, casacore, yt, fsspec |',
    '| Represent and calibrate | Units, epochs, coordinates, masks, uncertainty, detector responses, reference selection | Astropy, ERFA/SOFA, Starlink, CRDS, observatory pipelines |',
    '| Measure | Sources, spectra, time series, redshifts, shapes, map statistics and selection functions | Photutils, PypeIt, HEASoft, CASA, GalSim, TreeCorr |',
    '| Predict | Background cosmology, transfer functions, matter power, lensing, populations, radiation and instruments | CAMB, CLASS, CCL, lens codes, FSPS, radiative-transfer codes |',
    '| Simulate | Initial conditions, particles, meshes, gravity, hydro/MHD, spacetime, mock observations | MUSIC, GADGET, AREPO, RAMSES, Einstein Toolkit, AMUSE |',
    '| Infer and compare | Theory calls, likelihoods, covariance, priors, optimization, posterior sampling and diagnostics | Cobaya, CosmoSIS, SNANA, Bilby, samplers, GetDist, ArviZ |',
    '| Inspect and reproduce | Linked views, fit diagnostics, intermediate artifacts, workflow execution and lineage | DS9, TOPCAT, Glue, CARTA, Rubin Butler, ORAC-DR, workflow engines |', '',
    '## Capability overlap map', '']
for n,r in enumerate(rows,1):
    links=', '.join(f"[{records[int(i.split('-')[1])]['name']}]({records[int(i.split('-')[1])]['source_url']})" for i in r['catalogue_ids'])
    out += [f"### {n:02d}. {r['capability']}", '', links, '',
            f"**Relationship:** {r['relationship']}", '',
            f"**Potential shared work:** {r['consolidation_opportunity']}", '',
            f"**Keep explicit:** {r['distinctions_to_preserve']}", '']
out += ['## Repetition to inspect in actual workflows', '',
    'The following are concrete places to look for repeated execution. They are hypotheses for a future workflow audit, not measured findings from this survey.', '',
    '| Repeated work | What could be reused | What makes reuse valid |', '|---|---|---|',
    '| Every application reads and converts the same file | Decoded, typed observation objects and lazy views | Source bytes, schema, selected HDUs/columns, scaling, masks and units |',
    '| Multiple packages recalculate distances or expansion histories | A cached cosmological background solution | Full cosmological parameters, physical assumptions, constants and tolerance |',
    '| Several likelihoods separately call the same Boltzmann solver | A theory-product dependency graph | Model state, requested observables, grids, nonlinear prescription and solver settings |',
    '| Each fitter independently interpolates the same templates and filters | Reusable template grids and passband operators | Model version, calibration, wavelength frame, integration convention and interpolation |',
    '| PSF convolutions or FFT plans are repeatedly rebuilt | Prepared operators and transform plans | Kernel/image geometry, boundary conditions, normalization, precision and device |',
    '| The same covariance is factorized for every likelihood call | Cached factorization or linear operator | Covariance truly parameter-independent; same ordering, masks, normalization and numerical method |',
    '| Data are copied between C/Fortran/Python/Julia/Rust containers | Shared memory buffers and explicit ownership | Compatible strides, types, alignment, lifetime, masks, units and device placement |',
    '| Survey masks, pair counts and window operators are rebuilt | Versioned geometry and selection products | Identical objects, weights, cuts, estimator definitions and random catalogues |',
    '| Each pipeline downloads or parses calibration assets separately | A shared versioned calibration/data cache | Exact release, validity interval, instrument configuration and checksum |',
    '| Every application converts and plots posterior chains differently | Common weighted-sample and diagnostic schema | Correct weights, transforms, log-density conventions, priors and sampler metadata |', '',
    '## Consolidation conclusion', '',
    'The greatest broadly shared surface is below the individual scientific models: data access, scientific objects, calibration assets, geometry, numerical primitives, task execution and inference interfaces. Above it, a unified software unit can expose multiple named model and solver implementations. This combines the repeated plumbing while preserving alternative algorithms and the ability to compare them.', '',
    'No speedup estimate is claimed. A library dependency graph, representative end-to-end workflows and profiling would be needed to establish how much computation, memory movement or I/O is actually duplicated.', '',
    'See the [full catalogue](CATALOGUE.md), [overall analysis](REPORT.md), [source evidence](EVIDENCE.md), and [machine-readable overlap map](overlap-map.json).', '']
(ROOT/'OVERLAP-MAP.md').write_text('\n'.join(out))
print(f'Wrote {len(rows)} overlap families covering {len(set(i for r in rows for i in r["catalogue_ids"]))} curated identities.')
